apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-vol
  name: mysql-vol-pod
spec:
  containers:
  - image: mysql:5.7
    name: mysql
    env:
      - name: MYSQL_DATABASE
        value: accounts
      - name: MYSQL_ROOT_PASSWORD
        value: secret
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-volume
  volumes:
    - name: mysql-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate
