apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deploy
spec:
  template:
    metadata:
      name: rmq-ignored-pod-name
      labels:
        pod: rmq
    spec:
      containers:
        - name: rmq-container
          image: rabbitmq
          ports:
            - name: rmq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
  replicas: 1
  selector:
    matchLabels:
      pod: rmq
