apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-vol
  name: mysql-vol-pod2
spec:
  containers:
  - image: mysql:5.7
    name: mysql
    env:
      - name: get-from-conf
        valueFrom:
          configMapKeyRef:
            name: conf1
            key: MYSQL_DATABASE
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-volume
  volumes:
    - name: mysql-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate
