apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: dotfile-test-container
      image: redis
      env:
        - name: secret_env
          valueFrom:
            secretKeyRef:
              name: secret-file
              key: username
  restartPolicy: Never
